version: '3.9'

services:
  servidor_principal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Servidor principal
    command: python servidor.py
    container_name: servidor_principal

  servidor_pagos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Servidor de pagos
    command: python servidor_pagos.py
    container_name: servidor_pagos

  servidor_proveedor_externo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"  # Proveedor externo
    command: python servidor_proveedor_externo.py
    container_name: servidor_proveedor_externo

  servidor_proveedor_competencia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5004"  # Proveedor competencia
    command: python servidor_proveedor_competencia.py
    container_name: servidor_proveedor_competencia

  servidor_rastreo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5111:5111"  # Servidor de rastreo
    command: python servidor_rastreo.py
    container_name: servidor_rastreo

  servidor_tipo_cambio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5009:5009"  # Tipo de cambio
    command: python servidor_tipo_cambio.py
    container_name: servidor_tipo_cambio

  servidor_tse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"  # TSE
    command: python servidor_tse.py
    container_name: servidor_tse

  RetroNintendo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # RetroNintendo
    command: python RetroNintendo.py
    container_name: RetroNintendo

  servidor_comparar_precios:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5011:5011"  # Comparar precios
    command: python servidor_comparar_precios.py
    container_name: servidor_comparar_precios
