FROM python:3.9-slim

WORKDIR /app

COPY RetroNintendo.py /app
COPY requirements.txt /app

RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libodbc1 \
    odbcinst \
    msodbcsql17 && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 4000

CMD ["python", "RetroNintendo.py"]
